# Selecciona la imagen de Node.js
FROM node:14-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de tu aplicación al contenedor
COPY package.json yarn.lock ./
COPY src ./src
COPY prisma ./prisma

# Instala las dependencias
RUN yarn install --production

# Establece las variables de entorno
ENV NODE_ENV production
ENV PORT 3000

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE $PORT

# Ejecuta la aplicación
CMD ["node", "src/main.ts"]
